<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Imports" data-toc-modified-id="Imports-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Imports</a></span></li><li><span><a href="#Anlegen-+-Konvertierung" data-toc-modified-id="Anlegen-+-Konvertierung-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Anlegen + Konvertierung</a></span></li><li><span><a href="#Diverse-Arrays-erzeugen" data-toc-modified-id="Diverse-Arrays-erzeugen-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Diverse Arrays erzeugen</a></span></li><li><span><a href="#Attribute" data-toc-modified-id="Attribute-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Attribute</a></span><ul class="toc-item"><li><span><a href="#Indizierung" data-toc-modified-id="Indizierung-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Indizierung</a></span></li><li><span><a href="#Slicing" data-toc-modified-id="Slicing-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Slicing</a></span><ul class="toc-item"><li><span><a href="#Array-kopieren" data-toc-modified-id="Array-kopieren-4.2.1"><span class="toc-item-num">4.2.1&nbsp;&nbsp;</span>Array kopieren</a></span></li></ul></li><li><span><a href="#Umformen" data-toc-modified-id="Umformen-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Umformen</a></span></li><li><span><a href="#Verketten" data-toc-modified-id="Verketten-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Verketten</a></span><ul class="toc-item"><li><span><a href="#Addition,-Substraktion,-Division,-Multiplikation-&amp;-Modulu" data-toc-modified-id="Addition,-Substraktion,-Division,-Multiplikation-&amp;-Modulu-4.4.1"><span class="toc-item-num">4.4.1&nbsp;&nbsp;</span>Addition, Substraktion, Division, Multiplikation &amp; Modulu</a></span></li><li><span><a href="#Lineare-Algebra" data-toc-modified-id="Lineare-Algebra-4.4.2"><span class="toc-item-num">4.4.2&nbsp;&nbsp;</span>Lineare Algebra</a></span></li><li><span><a href="#Problem-horizontal" data-toc-modified-id="Problem-horizontal-4.4.3"><span class="toc-item-num">4.4.3&nbsp;&nbsp;</span>Problem horizontal</a></span></li></ul></li><li><span><a href="#Aufteilen" data-toc-modified-id="Aufteilen-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Aufteilen</a></span></li></ul></li><li><span><a href="#Funktionen" data-toc-modified-id="Funktionen-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Funktionen</a></span><ul class="toc-item"><li><span><a href="#UFuncs" data-toc-modified-id="UFuncs-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>UFuncs</a></span></li></ul></li><li><span><a href="#Multidimensionale-NumPy-Arrays" data-toc-modified-id="Multidimensionale-NumPy-Arrays-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Multidimensionale NumPy Arrays</a></span><ul class="toc-item"><li><span><a href="#Kleines-Anwendungunsbeispiel" data-toc-modified-id="Kleines-Anwendungunsbeispiel-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Kleines Anwendungunsbeispiel</a></span></li><li><span><a href="#Großes-Anwendungsbeispiel" data-toc-modified-id="Großes-Anwendungsbeispiel-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Großes Anwendungsbeispiel</a></span></li><li><span><a href="#Test-Float" data-toc-modified-id="Test-Float-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Test Float</a></span></li></ul></li></ul></div>

# Imports

In [1]:
%run Imports.ipynb

All good


# Anlegen + Konvertierung

In [3]:
np.array([2,3,4,5,6,7])

array([2, 3, 4, 5, 6, 7])

In [4]:
np.array([2,3.313,3,4,5])

# Sollten die Typen nicht übereinstimmen versucht NumPy sie zu konvertieren 

array([2.   , 3.313, 3.   , 4.   , 5.   ])

In [5]:
np.array([2,3,4,5,6.4,7], dtype=int)

# NumPy konvertiert die 6.4 in ein Integer Wert

array([2, 3, 4, 5, 6, 7])

# Diverse Arrays erzeugen

In [6]:
np.zeros(10, dtype=int)

# Mit 0 gefülltes Array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3, 5), dtype=float)

# Mit Einsen gefülltes 3x5-Array (Float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3, 5), 3.14)

# Mit 3.14 gefülltes 3x5-Array


array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
full_like_test_arr = np.ones((4, 3))
np.full_like(full_like_test_arr, 4)

# Array nach dem vorgegebenen Muster 4x3 erzeugen


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [10]:
np.arange(0, 20, 2)

# Array von 0 bis 18 in 2er Schritten

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.linspace(0, 1, 5)

# Array von 0 bis 1 in 5 gleich große Schritte eingeteilt

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.random((3, 3))

# 3x3-Array gleichmäßig verteilter Zufallszahlen zwischen 0 und 1

array([[0.56369565, 0.3226465 , 0.21701199],
       [0.61267394, 0.94077373, 0.69921792],
       [0.32226996, 0.66891554, 0.70291827]])

In [13]:
np.random.normal(0, 1, (3, 3))

# 3x3-Array normalverteilter Zufallszahlen mit
# Mittelwert 0 und Standardabweichung 1 erzeugen

array([[-0.65688071, -1.47378846, -1.81078806],
       [ 0.16743369,  1.5837651 ,  1.60835972],
       [ 0.72954633, -0.17090767,  0.14837451]])

In [14]:
np.random.randint(0, 10, (3, 3))

# 3x3-Array zufällige Integers aus dem
# Intervall [0, 10) erzeugen

array([[9, 6, 0],
       [3, 0, 2],
       [4, 3, 7]])

In [15]:
print(np.identity(3))
print("")
print(np.eye(3))

# 3x3-Einheitsmatrix erzeugen

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
arr = np.array([[1,2,3]])
arr_rep1 = np.repeat(arr,3, axis=0)
print(arr_rep1)

# Array wiederholen (Axis = 0 ist für Reihe)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Attribute

In [21]:
# %%capture # Ausgabe unterdrücken

np.random.seed(0) # Reproduzierbarkeit
x1 = np.random.randint(10, size=6) # Eindimensionales Array 
x2 = np.random.randint(10, size=(3, 4)) # Zweidimensionales Array 
x3 = np.random.randint(10, size=(3, 4, 5)) # Dreidimensionales Array

print("1D-Array\n",x1, "\n")
print("2D-Array\n",x2, "\n")
print("3D-Array\n",x3, "\n")

1D-Array
 [5 0 3 3 7 9] 

2D-Array
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

3D-Array
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]] 



In [23]:
print(f"Dimensions:\t {x3.ndim} \n Shape:\t {x3.shape} \n Size:\t {x3.size}")

Dimensions:	 3 
 Shape:	 (3, 4, 5) 
 Size:	 60


## Indizierung

In [24]:
print(x1)
print(f"letztes Element im Array: {x1[-1]}")
print(f"zweitletztes Element im Array: {x1[-2]}")


[5 0 3 3 7 9]
letztes Element im Array: 9
zweitletztes Element im Array: 7


In [25]:
print(x1)
print(f"Ersten zwei Elemente: {x1[:2]}") 
print(f"Ab dem zweiten Element (bis Ende): {x1[2:]}")
print(f"Teilmenge: {x1[2:4]}") 
print(f"Jedes zweite Element: {x1[::2]}")
print(f"Jedes zweite Element ab Index 1: {x1[1::2]}")

print(f"Alle Elemente in umgekehrter Reihenfolge: {x1[::-1]}")
print(f"Jedes Element in umgekehrter Reihenfolge ab Index 4: {x1[4::-1]}")


[5 0 3 3 7 9]
Ersten zwei Elemente: [5 0]
Ab dem zweiten Element (bis Ende): [3 3 7 9]
Teilmenge: [3 3]
Jedes zweite Element: [5 3 7]
Jedes zweite Element ab Index 1: [0 3 9]
Alle Elemente in umgekehrter Reihenfolge: [9 7 3 3 0 5]
Jedes Element in umgekehrter Reihenfolge ab Index 4: [7 3 3 0 5]


Bezug auf umgekehrte Reihenfolge (vorherige Cell)
* [5 0 3 3 7 9] => [9 7 3 3 0 5]
* Jedes Element in umgekehrter Reihenfolge ab Index 4
* [9 <b><i>7 3 3 0 5</i></b>]

In [26]:
print(x2[:, 0]) # Erste Spalte von x2
print(x2[0, :]) # Erste Zeile von x2
print(x2[0]) # entspricht x2[0, :]

[3 7 1]
[3 5 2 4]
[3 5 2 4]


## Slicing

Array-Slices sind keine Kopien der Array-Daten, sondern echte Views (Sichten). In diesem Punkt
unterscheidet sich das Slicing von NumPy-Arrays vom Slicing von Python-
Listen: Slices von Python-Listen sind nur Kopien

In [27]:
# Beispiel

print("Array:\n",x2,"\n")
x2_sub = x2[:2, :2]
print("Sub-Array:\n",x2_sub,"\n")
# Veränderung des ursprünglichen Arrays

x2_sub[0, 0] = 99
print("Wert 99 an der Stelle 0.0 reinschreiben\n")
print("Verändertes Sub-Array:\n",x2_sub,"\n")
print("Verändertes Array:\n",x2)

Array:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

Sub-Array:
 [[3 5]
 [7 6]] 

Wert 99 an der Stelle 0.0 reinschreiben

Verändertes Sub-Array:
 [[99  5]
 [ 7  6]] 

Verändertes Array:
 [[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Array kopieren

In [28]:
x2_sub_copy = x2[:2, :2].copy()
print("Kopiertes sub-Array:\n",x2_sub_copy,"\n")
x2_sub_copy[0, 0] = 42
print("Wert 42 an der Stelle 0.0 reinschreiben\n")
print("Kopiertes Sub-Array:\n",x2_sub_copy,"\n")
print("Ursprüngliches Array:\n",x2)


Kopiertes sub-Array:
 [[99  5]
 [ 7  6]] 

Wert 42 an der Stelle 0.0 reinschreiben

Kopiertes Sub-Array:
 [[42  5]
 [ 7  6]] 

Ursprüngliches Array:
 [[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Umformen

Eindimensionales Array in eine zweidimensionale Zeilen-oder Spaltenmatrix konvertieren mit Hilfe von der <b>reshape()-Methode</b> oder Slicing mit <b>newaxis</b>

In [29]:
x = np.array([1, 2, 3])
print("Array: ",x,"\n")
print("Zeilenvektor newaxis: ",x[np.newaxis, :],"\n")
print("Spaltenvektor newaxis:\n",x[:, np.newaxis],"\n")
print("Zeilenvektor reshape: ",x.reshape((1, 3)),"\n")
print("Spaltenvektor reshape:\n",x.reshape((3, 1)),"\n")

Array:  [1 2 3] 

Zeilenvektor newaxis:  [[1 2 3]] 

Spaltenvektor newaxis:
 [[1]
 [2]
 [3]] 

Zeilenvektor reshape:  [[1 2 3]] 

Spaltenvektor reshape:
 [[1]
 [2]
 [3]] 



Reshape verwendet -1 als Wert, um den Formwert zu bezeichnen, der die verbleibenden nicht spezifizierten Elemente verwenden wird. Wir könnten z.B. angeben, dass die erste Dimension die Länge 3 haben soll, und NumPy kann ausrechnen, dass die zweite Dimension die Länge 2 haben muss, und umgekehrt

In [30]:
arr1d = np.arange(2,10)
print(arr1d.reshape((2,-1)),"\n")
print(arr1d.reshape((-1,2)))

[[2 3 4 5]
 [6 7 8 9]] 

[[2 3]
 [4 5]
 [6 7]
 [8 9]]


## Verketten

Verkettung oder Vereinigung zweier Arrays in NumPy wird vornehmlich mithilfe der Routinen <b>np.concatenate</b>, <b>np.vstack</b>, <b>np.hstack</b> und <b>np.dstack</b>

<b>np.concatenate</b> nimmt ein Tupel oder eine Liste von Arrays als erstes Argument entgegen

In [31]:
# Beispiel np.concatenate

x = np.array([1, 2, 3]) 
y = np.array([33, 22, 11]) 
np.concatenate([x, y])

array([ 1,  2,  3, 33, 22, 11])

In [32]:
# vstack()
x = np.array([1, 2, 3]) 
grid = np.array([[9, 8, 7], [6, 5, 4]]) 
print("Arrays vertikal verketten:\n",np.vstack([x, grid]),"\n")

# hstack()
y = np.array([[99], [99]])
print("Arrays horizontal verketten:\n",np.hstack([grid, y]),"\n")

# dstack()
z = np.ones((2,2))
z_conc = np.zeros((2,2))
print("Arrays entlang der dritten Dimension verketten:\n",np.dstack([z, z_conc]))

Arrays vertikal verketten:
 [[1 2 3]
 [9 8 7]
 [6 5 4]] 

Arrays horizontal verketten:
 [[ 9  8  7 99]
 [ 6  5  4 99]] 

Arrays entlang der dritten Dimension verketten:
 [[[1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]]]


### Addition, Substraktion, Division, Multiplikation & Modulu

In [33]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [34]:
grid + 3 # Addition

array([[12, 11, 10],
       [ 9,  8,  7]])

In [35]:
grid - 12 # Substraktion

array([[-3, -4, -5],
       [-6, -7, -8]])

In [36]:
grid / 4 # Division

array([[2.25, 2.  , 1.75],
       [1.5 , 1.25, 1.  ]])

In [37]:
grid * 3 # Mulitplikation

array([[27, 24, 21],
       [18, 15, 12]])

In [38]:
grid % 4 # Modulu

array([[1, 0, 3],
       [2, 1, 0]], dtype=int32)

### Lineare Algebra

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [39]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [40]:
# Suche des Determinanten

c = np.identity(3)
np.linalg.det(c)

1.0

### Problem horizontal

Fehlermeldung: <br><br>
ValueError: all the input array dimensions except for the concatenation axis must match exactly
Das liegt daran, dass np.hstack nicht zwei Arrays mit <b>unterschiedlicher Zeilenanzahl</b> verketten kann.

<br><br>
$\begin{bmatrix} 1 & 1 & 1 \\ 1 & 1 & 1 \\ 1 & 1 & 1 \end{bmatrix}$ + 
$\begin{bmatrix} 2 & 2 & 2 \end{bmatrix}$ = ?
<br><br>

Wir können unsere neue Zeile auch nicht einfach transponieren (Spiegeln einer Matrix) , weil sie ein 
eindimensionales Array ist und ihre Transponierung die gleiche Form hat
wie das Original. Also müssen wir sie zuerst <b>umformen</b>

In [41]:
a = np.ones((3, 3))
b = np.array((2,2,2)).reshape(3,1)
print("Transponiertes Array:\n",b,"\n")
print("Zusammengesetztes Array:\n",np.hstack((a, b)))

Transponiertes Array:
 [[2]
 [2]
 [2]] 

Zusammengesetztes Array:
 [[1. 1. 1. 2.]
 [1. 1. 1. 2.]
 [1. 1. 1. 2.]]


## Aufteilen

Die Umkehrfunktion des Verkettens ist das Aufteilen, das in Form der
Funktionen <b>np.split, np.hsplit, np.vsplit und np.dsplit</b> implementiert ist. Dabei wird
jeweils eine Liste mit Indizes zur Beschreibung der Aufteilungspunkte übergeben

In [42]:
# split()
x = [1, 2, 3, 99, 99, 3, 2, 1]
print(x,"\n")
x1, x2, x3 = np.split(x, [3, 5])
print("Array gesplitet an Stelle 3 und 5:\n",x1, x2, x3,"\n","--------------------\n")

# vsplit()
grid = np.arange(16).reshape((4, 4))
print("Array vsplit + hsplit:\n",grid,"\n")
upper, lower = np.vsplit(grid,[2])
print("vsplit upper:\n",upper,"\n")
print("vsplit lower:\n",lower,"\n")

# hsplit()
left, right = np.hsplit(grid, [2]) 
print("hsplit left:\n",left,"\n") 
print("hsplit right:\n",right,"\n")

# dsplit()
dsplit_grid = np.arange(16.0).reshape(2, 2, 4)
print("dsplit Array:\n",dsplit_grid,"\n")
print("dsplit in zwei gleichgroße Arrays:\n",np.dsplit(dsplit_grid,2),"\n")

# print(np.dsplit(dsplit_grid, np.array([3, 6])),"\n\n") # Warum 6?
print(np.dsplit(dsplit_grid, np.array([3,]))) # Selbe Ergebnis wie [3,6]

[1, 2, 3, 99, 99, 3, 2, 1] 

Array gesplitet an Stelle 3 und 5:
 [1 2 3] [99 99] [3 2 1] 
 --------------------

Array vsplit + hsplit:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

vsplit upper:
 [[0 1 2 3]
 [4 5 6 7]] 

vsplit lower:
 [[ 8  9 10 11]
 [12 13 14 15]] 

hsplit left:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

hsplit right:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 

dsplit Array:
 [[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]] 

dsplit in zwei gleichgroße Arrays:
 [array([[[ 0.,  1.],
        [ 4.,  5.]],

       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2.,  3.],
        [ 6.,  7.]],

       [[10., 11.],
        [14., 15.]]])] 

[array([[[ 0.,  1.,  2.],
        [ 4.,  5.,  6.]],

       [[ 8.,  9., 10.],
        [12., 13., 14.]]]), array([[[ 3.],
        [ 7.]],

       [[11.],
        [15.]]])]


# Funktionen

Da Python eine dynamische, interpretierte Programmiersprache ist ist sie aufgrund der Flexibilität der Datentypen eine langsame Programmiersprache.

Es stellt sich heraus, dass nicht die Rechenoperationen selbst den Engpass verursachen, sondern die Typüberprüfung und die Funktionsaufrufe, die Python beispielsweise bei jedem Durchlauf einer Schleife erledigen muss. Bei jeder Berechnung eines Kehrwerts überprüft Python zunächst den Objekttyp und muss dann die richtige Funktion ermitteln, die für diesen Typ anzuwenden ist.

## UFuncs

NumPy stellt für viele Operationen komfortable Schnittstellen bereit, um auf genau diese Art statisch typisierter kompilierter Routinen zuzugreifen. Man spricht hier von einer vektorisierten Operation.

In [43]:
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

big_array = np.random.randint(1, 100, size=1000000) 
%timeit compute_reciprocals(big_array)
%timeit (1.0 / big_array)

1.66 s ± 33.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.71 ms ± 129 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Dieser vektorisierte Ansatz sorgt dafür, dass die Schleife durch den kompilierten Code ausgeführt wird, auf dem NumPy beruht, was zu einer sehr viel schnelleren Abarbeitung führt.

In NumPy sind vektorisierte Operationen durch UFuncs implementiert, deren
Hauptaufgabe es ist, wiederholt Berechnungen mit Werten in NumPy-Arrays
schnell auszuführen.

Bei UFuncs gibt es zwei Varianten (unäre (Einzelne) und binäre (Mehrere))

# Multidimensionale NumPy Arrays

## Kleines Anwendungunsbeispiel

Suppose we want to use climate data like the temperature, rainfall, and humidity to determine if a region is well suited for growing apples. A simple approach for doing this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions like the average temperature (in degrees Fahrenheit), rainfall (in millimeters) & average relative humidity (in percentage) as a linear equation.

<b>yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity</b>

We're expressing the yield of apples as a weighted sum of the temperature, rainfall, and humidity. This equation is an approximation since the actual relationship may not necessarily be linear, and there may be other factors involved. But a simple linear model like this often works well in practice.

Based on some statical analysis of historical data, we might come up with reasonable values for the weights w1, w2, and w3. Here's an example set of values:

In [44]:
weights = np.array([0.3, 0.2, 0.5])

Given some climate data for a region, we can now predict the yield of apples. Here's some sample data:

<img src="https://i.imgur.com/TXPBiqv.png" style="width:360px;">

To begin, we can define some variables to record climate data for a region.

In [45]:
climate_data = np.array([[73, 67, 43],
                        [91, 88, 64],
                        [87, 134, 58],
                        [102, 43, 37],
                        [69, 96, 70]])

# Reihe = Land
# Spaltenaufteilung = 1. Temperatur, 2. Regenfall, 3. Luftfeuchtigkeit 

In [46]:
climate_data.shape

(5, 3)

In [47]:
climate_data.dtype

dtype('int32')

In [48]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [49]:
# Alternativ
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

## Großes Anwendungsbeispiel

In [ ]:
# Fehlermeldung SSL: CERTIFICATE_VERIFY_FAILED beseitigen
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

In [55]:
urllib.request.urlretrieve("https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv",
                          "data/numpy/climate.txt")

('data/climate.txt', <http.client.HTTPMessage at 0x23c48606850>)

In [56]:
climate_data_big = np.genfromtxt("data/numpy/climate.txt", delimiter=",", skip_header=1)

In [57]:
climate_data_big

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [58]:
weights_big = np.array([0.3, 0.2, 0.5])

In [59]:
yields = climate_data_big @ weights_big

Spalte hinzufügen zum Array "climate_data_big"

In [60]:
yields.shape

(10000,)

In [61]:
climate_results = np.concatenate((climate_data_big, yields.reshape(10000,1)), axis=1)
# Reshape von (10000,) zu (10000,1)

In [62]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

Resultat speichern in einer .txt-Datei

In [63]:
np.savetxt("data/numpy/climate_results.txt",
          climate_results,
          fmt="%.2f",
          header="Temperatur, Regenfall, Luftfeuchtigkeit, Ernte_Aepfel")

## Test Float

In [ ]:
arr_test = np.array([[[11, 12, 13], [13, 14, 15]],
                    [[15, 16, 17], [17, 18, 19.5]]])
# Letzte Zahl ist eine Float-Zahl

In [ ]:
arr_test

array([[[11. , 12. , 13. ],
        [13. , 14. , 15. ]],

       [[15. , 16. , 17. ],
        [17. , 18. , 19.5]]])

In [ ]:
arr_test.dtype

dtype('float64')